In [1]:
import torch

In [18]:
eps = torch.load("pointmaze_wo_time/PointMaze_eps.pt")

In [20]:
eps[4][5]

{'overall_reward': 95.80000000000001,
 'manager': [(0,
   array([ 9.9658966e-05, -3.7752509e-02,  9.9926573e-01], dtype=float32),
   array([3.49651417, 2.65245429])),
  (10,
   array([1.7168832, 0.8638289, 0.2120663], dtype=float32),
   array([3.44617313, 3.49978155])),
  (20,
   array([1.6001818 , 2.3086522 , 0.31304562], dtype=float32),
   array([-1.49940231, -0.66023627])),
  (30,
   array([0.7446821 , 1.5046086 , 0.05662641], dtype=float32),
   array([3.49705657, 3.21055239])),
  (40,
   array([0.6515317 , 2.4482267 , 0.30863127], dtype=float32),
   array([-1.42823422,  0.40991685]))],
 'worker': [(0,
   array([ 9.96589661e-05, -3.77525091e-02,  9.99265730e-01,  3.49651417e+00,
           2.65245429e+00]),
   array([ 0.99712133, -0.6200527 ], dtype=float32)),
  (1,
   array([ 0.21985972, -0.15542245,  0.92175913,  3.27675411,  2.77012423]),
   array([0.9959148 , 0.35249582], dtype=float32)),
  (2,
   array([ 0.46311915, -0.20848107,  0.96582115,  3.03349468,  2.82318285]),
   array